standard_time:
    year: 2025
    month: 4
    day: 25
    hour: 16
    minute: 0

problem_definition:
    num_days: 6
    hotel_index: 0
    total_hours_in_day: 12
    solve_time_in_minutes: 40
    use_gurobi: False
    reduce_no_of_possible_trips: 0.4

execution_pipeline:
    fetch_distances: False
