
line-length = 120
target-version = "py311"
lint.select = [
    "ANN", # annotations
    "ARG", # arguments
    "B", # bugbear
    "C", # comprehensions
    "D", # docstrings
    "E", # style errors
    "F", # flakes
    "I", # import sorting
    "RUF100", # meta
    "S", # Checks on security (bandit)
    "PD", # pandas
    "N", # naming
    "U", # upgrade
    "W", # style warnings
    "YTT", # sys.version
    "RET", # Checks on return statements
    "SIM", # Simplify code
    "ASYNC", # Checks on async code
    "BLE", # Blind except statement
]
lint.ignore = [
    "ANN002", # Missing type annotation for *args
    "ANN003", # Missing type annotation for **kwargs
    "ANN101", # Missing type annotation for `self` in method
    "ANN102", # Missing type annotation for `cls` in classmethod
    "ANN401", # Dynamically typed expressions (typing.Any) are disallowed
    "B024", # Abstract base class withtout abstract methods
    "C408", # Unnecessary `dict` call (rewrite as a literal)
    "D105", # Missing docstring in magic method
    "D203", # 1 blank line required before class docstring
    "D213", # Multi-line docstring summary should start at the second line
    "E402", # Module level import not at top of file
    "N818", # Exception name should be named with an Error suffix
    "PD901", # Use df as variable name
    "RET504", # Unnecessary assignment before `return` statement
    "S101",  # Use of assert
    "S301", # Pickle
    "D413", # Blank line after last section
    "D107", # Missing docstring in __init__
    "N999"
]
